# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 34fa29355b8ed63ab2942d92c0a628a30f63f5183afffa49d4dcdefb87bebfe195e7651fa1ea9315f4a620b4f5ec80adae622f9c577801b85c277899db810085

test:
  secret_key_base: e2b6045cc3ef9c350a1a676e37e0e969a466383e384661165110e11c56a4569e7464850d2b687afaf6fa89944cd04f21bf875e4d11dbc66f0ef5ab9cade2441a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
